### ISSUE TITLE
Some bugs with subscription page

### ISSUE THREAD

**Issue by Cryental** [topa-LE/plesk_blue_dark_theme#1]
Hello. I'm getting bugs with new version of Plesk. Is it possible to fix this problem? Attached a screenshot below:
![9B07E061-A378-450C-983F-D783FE8850F6](https://user-images.githubusercontent.com/44664655/116533140-d72cd380-a902-11eb-9344-4268cee01939.jpeg)

**Comment by flcaw** [comment]
Was this fixed?

**Comment by Cryental** [comment]
Nope, still this bug is there since the author didn't update yet.

**Comment by topa-LE** [comment]
Can't see the exact error on the screenshot unfortunately. What is it exactly so that this can be fixed?

**Comment by flcaw** [comment]
Btw I tried to install the theme yesterday on plesk 18 but it doesn't even show up on skins. I even activated it.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by topa-LE** [comment]
Follow the installation instructions exactly. Even in Plesk you can not activate this theme, because after the install this is "Default". So please install exactly according to instructions ...

**Comment by flcaw** [comment]
I did dear but it doesn't seem to work :(

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by flcaw** [comment]
Any solution? @topa-LE

**Comment by topa-LE** [comment]
> Any solution? @topa-LE

Maybe you don't understand exactly what to do. A custom theme can and will never be displayed in the Plesk backend. Therefore you can't activate it there either.

What exactly have you tried? Did you unzip the master.zip and then copy it via SSH to the exact folder. Write exactly what was done, because with: "I tried it, I can do little". Thanks

**Comment by Cryental** [comment]
Hello @topa-LE! I will test your new update now and let you know soon. Did you fix bugs above what I posted?

**Comment by topa-LE** [comment]
> I will test your new update now and let you know soon. Did you fix bugs above what I posted?

This is smartphone, which I only use desktop, unfortunately I can not say what class this is. You must mean the Padding or Margin distance in the screenshot?

**Comment by topa-LE** [comment]
> Hello @topa-LE! I will test your new update now and let you know soon. Did you fix bugs above what I posted?

I have tried to reproduce your problem. However, I don't know exactly which setting option you have selected there. Currently the view fits for me.
![plesk-mobi-viewsl](https://user-images.githubusercontent.com/63888024/131520952-e3b9b2b2-1096-4d0d-9768-24c54d2f626b.jpg)

**Comment by Cryental** [comment]
yeah with your recent patch now it's fine :D

**Comment by topa-LE** [comment]
> yeah with your recent patch now it's fine :D

perfect ;-)
